#
# This pulled from LambdAurora's LambdaBetterGrass
# Thanks
# 

name: Gradle Build

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'

jobs:
  build:
    strategy:
      matrix:
        java: [ 17, 20 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew build
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: ./build/libs/
