#
# This workflow pulls from LambdAurora's LambdaBetterGrass and Sodium
# 

name: Gradle Build

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Cache/Uncache Building Tweaks
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/loom-cache
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build With Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --parallel --stacktrace
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: ./build/libs/*.jar
