#
# This workflow pulls from LambdAurora's LambdaBetterGrass and Sodium
#

name: Release

on: [workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@main
      - name: Release With Gradle
        run: ./gradlew build github modrinth -Pbuild.release=true --parallel --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CHANGELOG: ${{steps.build_changelog.outputs.changelog}}
